EXECUTABLE = imagewarping
OBJS = build/CUDAPatchSolverWarping.o build/CUDAWarpingSolver.o build/mLibSource.o build/main.o build/PatchSolverWarping.o build/TerraSolverWarping.o build/WarpingSolver.o
include ../maketemplate.inc
