SRC = .
EXECUTABLE = bundleadjustment
OBJS = build/bundlerManager.o build/featureExtractor.o build/imagePairCorrespondences.o build/mLibSource.o build/main.o

FLAGS += -I/usr/local/include
LFLAGS += -L/usr/local/lib -lopencv_xfeatures2d -lceres -lopencv_core -lglog
include ../maketemplate.inc


