EXECUTABLE = shapefromshading
OBJS = build/CUDAImageSolver.o	build/CUDAPatchSolverWarping.o build/mLibSource.o build/main.o build/SFSSolver.o build/PatchSolverWarping.o build/SimpleBuffer.o
include ../maketemplate.inc
